ALTER TABLE users ADD COLUMN IF NOT EXISTS approval_status VARCHAR(20) NOT NULL DEFAULT 'APPROVED';
ALTER TABLE users ADD COLUMN IF NOT EXISTS approval_reason VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS review_deadline TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locale VARCHAR(5) NOT NULL DEFAULT 'fr';
UPDATE users SET role = 'VISITOR' WHERE role = 'USER';
UPDATE users SET approval_status = 'APPROVED', approved_at = COALESCE(approved_at, created_at) WHERE role IN ('ADMIN', 'VISITOR');
CREATE INDEX IF NOT EXISTS idx_users_approval_status ON users (approval_status, created_at);

CREATE TABLE IF NOT EXISTS professional_profiles (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  profile_type VARCHAR(20) NOT NULL, display_name VARCHAR(120) NOT NULL, birth_date DATE,
  gender VARCHAR(40), location VARCHAR(160), bio TEXT, languages TEXT, height_cm SMALLINT,
  hair VARCHAR(60), eyes VARCHAR(60), services TEXT, availability VARCHAR(500), website VARCHAR(300),
  price_from DECIMAL(10,2), price_to DECIMAL(10,2),
  business_name VARCHAR(160), legal_name VARCHAR(160), segment VARCHAR(100),
  business_address VARCHAR(200), business_hours VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_professional_profiles_type ON professional_profiles (profile_type, display_name);

CREATE TABLE IF NOT EXISTS profile_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  media_type VARCHAR(10) NOT NULL, file_name VARCHAR(255) NOT NULL, content_type VARCHAR(120) NOT NULL,
  size_bytes BIGINT NOT NULL, media_data BYTEA NOT NULL, position SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_profile_media_user ON profile_media (user_id, media_type, position, id);

CREATE TABLE IF NOT EXISTS favorites (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  profile_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (user_id, profile_user_id)
);
CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participant_one_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  participant_two_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (participant_one_id, participant_two_id)
);
CREATE INDEX IF NOT EXISTS idx_conversations_updated ON conversations (updated_at);
CREATE TABLE IF NOT EXISTS conversation_members (
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  archived_at TIMESTAMPTZ, last_read_at TIMESTAMPTZ,
  PRIMARY KEY (conversation_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_conversation_members_user ON conversation_members (user_id, archived_at);
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages (conversation_id, id);
CREATE TABLE IF NOT EXISTS blocked_users (
  blocker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  blocked_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (blocker_id, blocked_id)
);
CREATE TABLE IF NOT EXISTS user_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reported_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reason VARCHAR(80) NOT NULL, details VARCHAR(1000), status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_reports_status ON user_reports (status, created_at);
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash CHAR(64) NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens (user_id, created_at);
CREATE TABLE IF NOT EXISTS email_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, recipient VARCHAR(160) NOT NULL,
  template VARCHAR(60) NOT NULL, locale VARCHAR(5) NOT NULL, subject VARCHAR(255) NOT NULL,
  body TEXT NOT NULL, delivery_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, sent_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_email_outbox_status ON email_outbox (delivery_status, created_at);
