ALTER TABLE professional_profiles ADD COLUMN IF NOT EXISTS weight_kg SMALLINT NULL;
ALTER TABLE professional_profiles ADD COLUMN IF NOT EXISTS bust_cm SMALLINT NULL;
ALTER TABLE professional_profiles ADD COLUMN IF NOT EXISTS waist_cm SMALLINT NULL;
ALTER TABLE professional_profiles ADD COLUMN IF NOT EXISTS hips_cm SMALLINT NULL;
ALTER TABLE professional_profiles ADD COLUMN IF NOT EXISTS origin VARCHAR(80) NULL;
ALTER TABLE professional_profiles ADD COLUMN IF NOT EXISTS interests TEXT NULL;
ALTER TABLE professional_profiles ADD COLUMN IF NOT EXISTS contact_options TEXT NULL;
ALTER TABLE professional_profiles ADD COLUMN IF NOT EXISTS purchase_count INT NOT NULL DEFAULT 0;
ALTER TABLE professional_profiles ADD COLUMN IF NOT EXISTS views_count INT NOT NULL DEFAULT 0;
ALTER TABLE professional_profiles ADD COLUMN IF NOT EXISTS verified BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  name VARCHAR(120) NOT NULL,
  category VARCHAR(60) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  original_price DECIMAL(10,2) NULL,
  image_url VARCHAR(500) NOT NULL,
  secondary_image_url VARCHAR(500) NULL,
  tag VARCHAR(40) NULL,
  sale_label VARCHAR(40) NULL,
  reviews INT NOT NULL DEFAULT 0,
  purchase_count INT NOT NULL DEFAULT 0,
  likes INT NOT NULL DEFAULT 0,
  description TEXT NULL,
  store_name VARCHAR(120) NULL,
  store_address VARCHAR(160) NULL,
  store_city VARCHAR(80) NULL,
  store_segment VARCHAR(80) NULL,
  store_hours VARCHAR(120) NULL,
  product_type VARCHAR(80) NULL,
  material VARCHAR(160) NULL,
  available_sizes VARCHAR(120) NULL,
  color_options VARCHAR(120) NULL,
  stock_status VARCHAR(80) NULL,
  shipping_note VARCHAR(160) NULL,
  care_instructions VARCHAR(160) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE products ADD COLUMN IF NOT EXISTS store_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
CREATE INDEX IF NOT EXISTS idx_products_category ON products (category, is_active);
CREATE INDEX IF NOT EXISTS idx_products_store ON products (store_user_id, is_active);

CREATE TABLE IF NOT EXISTS product_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  role VARCHAR(20) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  content_type VARCHAR(120) NOT NULL,
  size_bytes BIGINT NOT NULL,
  image_data BYTEA NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_product_images_product_role UNIQUE (product_id, role)
);

CREATE TABLE IF NOT EXISTS marketplace_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id BIGINT NULL REFERENCES products(id) ON DELETE SET NULL,
  profile_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  order_type VARCHAR(20) NOT NULL,
  amount DECIMAL(10,2) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_orders_buyer ON marketplace_orders (buyer_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_orders_product ON marketplace_orders (product_id, status);
CREATE INDEX IF NOT EXISTS idx_orders_profile ON marketplace_orders (profile_user_id, status);

CREATE TABLE IF NOT EXISTS profile_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reviewer_name VARCHAR(80) NOT NULL,
  body VARCHAR(500) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_profile_reviews_profile ON profile_reviews (profile_user_id, created_at);
