CREATE TABLE IF NOT EXISTS responsive_image_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_media_id BIGINT NULL REFERENCES profile_media(id) ON DELETE CASCADE,
  product_image_id BIGINT NULL REFERENCES product_images(id) ON DELETE CASCADE,
  width SMALLINT NOT NULL CHECK (width > 0),
  height SMALLINT NOT NULL CHECK (height > 0),
  content_type VARCHAR(40) NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
  image_data BYTEA NOT NULL,
  source_hash CHAR(64) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_responsive_owner CHECK ((profile_media_id IS NULL) <> (product_image_id IS NULL)),
  CONSTRAINT uk_responsive_profile_width UNIQUE (profile_media_id, width),
  CONSTRAINT uk_responsive_product_width UNIQUE (product_image_id, width)
);
CREATE INDEX IF NOT EXISTS idx_responsive_source_hash ON responsive_image_variants (source_hash);
