CREATE TABLE IF NOT EXISTS user_exclusions (
  owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  excluded_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (owner_id, excluded_user_id),
  CHECK (owner_id <> excluded_user_id)
);
CREATE INDEX IF NOT EXISTS idx_user_exclusions_target
  ON user_exclusions (excluded_user_id, owner_id);

CREATE TABLE IF NOT EXISTS escort_appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escort_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(160) NOT NULL,
  client_name VARCHAR(120) NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  location VARCHAR(200),
  notes VARCHAR(2000),
  status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (ends_at > starts_at)
);
CREATE INDEX IF NOT EXISTS idx_escort_appointments_owner_start
  ON escort_appointments (escort_user_id, starts_at, id);
